### PR TITLE
cargo: stop pinning revisions and minor versions

### PR DESCRIPTION
**Pull request by johanot**
Well: pinning wasn't reeeeally happening, because cargo won't PIN depedencies unless the equal sign is used ("=<version"). Without the equals-symbol its more like a "hint" to Cargo. But, we might as well hint something less conservative and get more updates.

### CODE REVIEW

**Comment by johanot** [comment]
Now builds with cargo, but not crate2nix. Let's consider switching to crane.

**Comment by johanot** [comment]
@srhb crate2nix -> crane . This will spawn some work on your side, but it should be ok. See individual commits for descriptions of what is done to make this branch build.

**Comment by srhb** [comment]
Gotcha, I'll take a look next week if not before :)

**Review by srhb — APPROVED** [review]

**Comment by srhb** [comment]
Pushed a merge to fixup conflicts to your branch, hope that's fine. Will merge once pipeline completes.

**Pull request merged**
